// Code generated by mockery 2.9.4. DO NOT EDIT.

package mocks

import (
	admin "auto_traveler/bussiness/admin"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// FindByEmail provides a mock function with given fields: ctx, email
func (_m *Repository) FindByEmail(ctx context.Context, email string) (admin.Domain, error) {
	ret := _m.Called(ctx, email)

	var r0 admin.Domain
	if rf, ok := ret.Get(0).(func(context.Context, string) admin.Domain); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Get(0).(admin.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *Repository) FindByID(ctx context.Context, id int) (admin.Domain, error) {
	ret := _m.Called(ctx, id)

	var r0 admin.Domain
	if rf, ok := ret.Get(0).(func(context.Context, int) admin.Domain); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(admin.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
