// Code generated by mockery 2.9.4. DO NOT EDIT.

package mocks

import (
	events "auto_traveler/bussiness/events"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Find provides a mock function with given fields: ctx, eventType
func (_m *Repository) Find(ctx context.Context, eventType string) ([]events.Domain, error) {
	ret := _m.Called(ctx, eventType)

	var r0 []events.Domain
	if rf, ok := ret.Get(0).(func(context.Context, string) []events.Domain); ok {
		r0 = rf(ctx, eventType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]events.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, eventType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
